name: Pathfinder Auto-Scraping

on:
  schedule:
    # Se lance tous les jours vers 22h17 (heure UTC)
    - cron: '17 22 * * *'
  workflow_dispatch: # Permet de lancer le robot manuellement depuis GitHub

  # Définition des variables d'environnement globales pour TOUS les serveurs
env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  FT_CLIENT_ID: ${{ secrets.FT_CLIENT_ID }}
  FT_CLIENT_SECRET: ${{ secrets.FT_CLIENT_SECRET }}

jobs:
  # 🤖 Agent 1 : France Travail
  agent_ft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Mets ta version
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Lancement Pipeline FT
        run: |
          python scrapers/francetravail/api_francetravail.py
          python scrapers/francetravail/clean_francetravail.py

  # 🤖 Agent 2 : Welcome to the Jungle
  agent_wttj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Lancement Pipeline WTTJ
        run: |
          python scrapers/wttj/api_wttj.py          
          python scrapers/wttj/clean_wttj.py

  # 🤖 Agent 3 : APEC
  agent_apec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Lancement Pipeline APEC
        run: |
          python scrapers/apec/crawler_apec.py
          python scrapers/apec/scraper_apec.py
          python scrapers/apec/clean_apec.py

  # 🧹 Agent 4 : Updater de WTTJ (Cadenas Temporel)
  agent_wttj_updaters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Vérification de l'ancien stock
        run: |
          python scrapers/wttj/updater_wttj.py
          
  # 🧹 Agent 5 : Updater de APEC (Cadenas Temporel)
  agent_apec_updaters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Vérification de l'ancien stock
        run: |
          python scrapers/apec/updater_apec.py
  # 🧹 Agent 6 : Updater de FranceTravail (Cadenas Temporel)
  agent_ft_updaters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Vérification de l'ancien stock
        run: |
          python scrapers/francetravail/updater_francetravail.py
  # 🌪️ Agent 7 : LA FUSION (Tourne à la toute fin)
  agent_clean_all:
    needs: [agent_ft, agent_wttj, agent_apec]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installation des dépendances
        run: pip install -r requirements.txt     
               
      - name: Nettoyage global
        run: python clean_all.py # ⚠️ IMPORTANT : Si ton fichier s'appelle différemment ou est dans un dossier, corrige ce chemin (ex: python scrapers/fusion.py)